-- +goose Up
ALTER TABLE posts
    ADD COLUMN tags VARCHAR(100)[];

ALTER TABLE posts
    ADD COLUMN updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW();

-- +goose Down
ALTER TABLE posts
    DROP COLUMN IF EXISTS tags;
ALTER TABLE posts
    DROP COLUMN IF EXISTS updated_at;
